[tool.isort]
profile = "black"
src_paths = ["admin_webapp"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rPaq"
testpaths = ["tests"]
python_files = ["*.py"]
markers = ["slow: mark test as slow", "fast: mark test as fast", "ud_test: for urgency detection"]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning"
]
